name: Build-Test-Deploy Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: running first jobs
        run: |
          echo "This is the first job running on push to main or manual trigger."
          echo "Setting up environment..."
          apt-get update && apt-get install -y python3 python3-pip

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: running second job
    
        run: |
          Write-Outpt "Setting up environment..."
          choco install python

  deploy:
    needs: test
    runs-on: macos-latest
    steps:
      - name: running third job
        
        run: |
          echo "This is the third job running after the second job completes."
          echo "Setting up environment..."
          brew install python3
